plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-sorted_methods_by_call
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/api/*
    - spec/extensions/*
